version: "3.7"

# https://cardbox.sova.dev

volumes:
  postgres-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/cardbox/postgres"
      o: bind

services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./services/traefik/config.yml:/etc/traefik/config.yml:ro
    labels:
      traefik.http.routers.traefik-secure.tls.certresolver: "le"
      traefik.http.routers.traefik-secure.middlewares: "dashboard-auth@file"

  grafana:
    labels:
      traefik.http.routers.grafana.tls.certresolver: "le"

  api-internal:
    image: "docker.pkg.github.com/cardbox/backend/api-internal:latest"
    labels:
      traefik.http.routers.api-internal.tls.certresolver: "le"

  frontend:
    image: "docker.pkg.github.com/cardbox/frontend/main:latest"
    labels:
      traefik.http.routers.frontend.tls.certresolver: "le"
    environment:
      PUBLIC_URL: https://cardbox.sova.dev
      IMAGE_URL: https://cardbox.sova.dev/images
      DEBUG: "true"
