version: "3.7"

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/data/images"
      o: bind

  facade-webroot:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/data/webroot"
      o: bind

  postgres-storage:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/data/postgres"
      o: bind

networks:
  entry:

services:
  database:
    container_name: cardbox-database
    image: postgres:11.5
    restart: always
    volumes:
      - "postgres-storage:/var/lib/postgresql/data"
    networks:
      - entry
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"

  api-internal:
    container_name: cardbox-api-internal
    image: docker.pkg.github.com/cardbox/backend/api-internal:latest
    restart: always
    expose:
      - "9008"
    depends_on:
      - database
    networks:
      - entry
    environment:
      CARDBOX_DATABASE__DATABASE: ${POSTGRES_DB}
      CARDBOX_DATABASE__HOST: database
      CARDBOX_DATABASE__PASSWORD: ${POSTGRES_PASSWORD}
      CARDBOX_DATABASE__POOL_SIZE: 4
      CARDBOX_DATABASE__USER: ${POSTGRES_USER}
      CARDBOX_MODE: production
      CARDBOX_SERVER__HOST: "0.0.0.0"
      CARDBOX_SERVER__PORT: "9008"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      RUST_LOG: info

  frontend:
    container_name: cardbox-frontend
    image: docker.pkg.github.com/cardbox/frontend/main:latest
    depends_on:
      - api-internal
    expose:
      - "3000"
    networks:
      - entry
    environment:
      PUBLIC_URL: https://cardbox.local
      IMAGE_URL: https://cardbox.local/images
      BACKEND_URL: http://cardbox-api-internal:9008

  facade:
    container_name: cardbox-facade
    image: docker.pkg.github.com/cardbox/releases/facade:latest
    ports:
      - 443:443
      - 80:80
    depends_on:
      - api-internal
      - frontend
    networks:
      entry:
        aliases:
          - cardbox.local
    volumes:
      - "${PWD}/tls/cardbox.crt:/var/lib/cardbox/tls/cardbox.crt"
      - "${PWD}/tls/cardbox.pem:/var/lib/cardbox/tls/cardbox.pem"
      - "${PWD}/tls/dhparam.pem:/etc/nginx/ssl/dhparam.pem"
      - image-storage:/images
      - facade-webroot:/webroot
    environment:
      SERVER_NAME: cardbox.local
      MAIN_UPSTREAM: cardbox-frontend:3000
      API_INTERNAL_UPSTREAM: cardbox-api-internal:9008