global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]
  - job_name: 'traefik'
    static_configs:
      - targets: [ 'traefik:8082' ]
  - job_name: 'api-internal'
    static_configs:
      - targets: [ 'api-internal:9110' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3100' ]
  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgresql-exporter:9187' ]
