http:
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin_cardbox:$2y$10$IVNHfSfHJ4DRNOU7y4HEqeeq16fiCPRsMyWYSEMuHaWm98jcBnhNO"
    api-internal-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/internal"
    api-public-stripprefix:
      stripPrefix:
        prefixes:
          - "/v0"
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        isDevelopment: false

