global:
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true

log:
  level: DEBUG

metrics:
  prometheus:
    entryPoint: metrics

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
    network: "releases_cardbox"

  file:
    filename: /etc/traefik/config.yml
    watch: true

entryPoints:
  metrics:
    address: :8082
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    http:
      middlewares:
        - security-headers@file

certificatesResolvers:
  le:
    acme:
      email: mail@sergeysova.com
      storage: /tls/acme.json
      tlsChallenge: true
      httpChallenge:
        entryPoint: web

tracing:
  serviceName: traefik
  jaeger:
    samplingParam: 1
    localAgentHostPort: otel-collector:6831
