
name: Deploy Prod

on:
  push:
    branches-ignore:
      - master
    paths:
      - "docker-compose.yaml"
      - "dev.yaml"
      - ".github/workflows/dev-deploy.yml"
      - "services/*"
  workflow_dispatch:


jobs:
  deploy:
    # Restrict deploy to prod
    if: contains('["Drevoed","sergeysova"]', github.actor)
    name: Deploy ${{ github.event.client_payload.github.repository }}
    runs-on: [prod]
    defaults:
      run:
        working-directory: /home/www/cardbox-releases
    env:
      DOMAIN_NAME: 'cardbox.dev'
      CARDBOX_ACCESSO__URL: 'https://accesso.app'
      CARDBOX_ACCESSO__CLIENT_ID: '00000000-0000-4000-acce-000000009100'
      CARDBOX_ACCESSO__REDIRECT_BACK_URL: 'https://cardbox.dev/accesso/done'
      CARDBOX_ACCESSO__CLIENT_SECRET: 'CardboxDev'
      CARDBOX_ACCESSO__SSL_VALIDATE: 'false'
      DATABASE_HOST: 'database'
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub Deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment: development

      - uses: sergeysova/deployment-status@releases/v1.1
        name: Deployment progress
        with:
          token: '${{ github.token }}'
          state: in_progress
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - uses: actions/checkout@v2

      - name: Docker Compose
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker login ghcr.io --username ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          export POSTGRES_DB="${{ secrets.DEV_DB }}"
          export POSTGRES_USER="${{ secrets.DEV_DB_USER }}"
          export POSTGRES_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}"
          docker-compose -f docker-compose.yaml -f prod.yaml pull
          docker-compose -f docker-compose.yaml -f prod.yaml build
          docker-compose -f docker-compose.yaml -f prod.yaml up -d --remove-orphans

      - uses: sergeysova/deployment-status@releases/v1.1
        name: Deployment success
        if: success()
        with:
          token: '${{ github.token }}'
          environment_url: https://cardbox.dev
          state: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - uses: sergeysova/deployment-status@releases/v1.1
        name: Deployment failure
        if: failure()
        with:
          token: '${{ github.token }}'
          state: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
